### PR TITLE
Remove test_ prefix from tests

### LINKED ISSUE #1720: Remove test_ prefix from test functions
As far as I can tell, this prefix is not idiomatic.
All test functions are annotated with `#[test]`, so it's not necessary for identification.

After a quick search, I couldn't find any considered-to-be-idiomatic sources which actually do this.
For example, [the official book doesn't](https://doc.rust-lang.org/book/ch11-01-writing-tests.html?search=test_) in its chapter on testing.

### PR DESCRIPTION
**Pull request by senekor**
[no important files changed]

closes #1720

### CODE REVIEW

**Comment by senekor** [comment]
Current dependencies on/for this PR:
* auto-sync
  * **PR #1723** <a href="https://app.graphite.dev/github/pr/exercism/rust/1723" target="_blank">Graphite</a> 
    * **PR #1727** <a href="https://app.graphite.dev/github/pr/exercism/rust/1727" target="_blank">Graphite</a>  👈
      * **PR #1726** <a href="https://app.graphite.dev/github/pr/exercism/rust/1726" target="_blank">Graphite</a> 
      * **PR #1725** <a href="https://app.graphite.dev/github/pr/exercism/rust/1725" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/exercism/rust/1727?utm_source=stack-comment).

**Comment by ErikSchierboom** [comment]
@senekor Looking at https://github.com/exercism/rust/commit/62d74800a5280237966f2f7bfaf495e4cf72ff45, it looks like the `[no important files changed]` marker is missing from the commit :( This means that we'll have a huge number of solutions being processed.

**Comment by senekor** [comment]
Oh noooo :fearful: how did I screw that up :sob:

**Comment by senekor** [comment]
It looks like I had the line in the PR description, but not in the commit message body. I presume when there is only one commit, this repo is setup to pick the body of the single commit, not the PR description. I'm used to the latter, but should've double checked...

**Comment by ErikSchierboom** [comment]
Well, lesson learned I guess! It's easy to make this mistake.

**Comment by MatthijsBlom** [comment]
> It's easy to make this mistake.

I proposed to make `[no important files changed]` the default a while ago. This same mistake is going to be made again many, many times.

**Pull request merged**
