### PR TITLE
Add filalex77 to maintainers.json

### PR DESCRIPTION
**Pull request by filalex77**
Related to #913

---
This change is [Reviewable](https://reviewable.io/reviews/exercism/rust/918)

### CODE REVIEW

**Comment by coriolinus** [comment]
Nope, I'm not the one with authority to actually add you to the maintainers list, and I haven't checked if you have the authority. Still, I think it's good symbolism if your first act as a maintainer is to merge yourself into the maintainers list.

**Comment by filalex77** [comment]
I think it's a chicken and egg problem: this PR needs to be merged in order for maintainers-sync bot to add me to the proper team so I get the rights to merge PRs in this repo...

**Comment by filalex77** [comment]
cc @exercism/rust: can somebody guide me into the direction of how this needs to be done? Thanks a lot.

**Comment by TheDarkula** [comment]
Welcome :)

**Pull request merged**
