### PR TITLE
README: minor typos

### PR DESCRIPTION
**Pull request by xakon**

### CODE REVIEW

**Comment by coriolinus** [comment]
@xakon Thanks for contributing this! Unfortunately, this will break our CI if you just make the changes here. Before I merge this, it will be necessary to update the [problem specifications repo](https://github.com/exercism/problem-specifications/). Are you willing to also open a PR there?

**Comment by coriolinus** [comment]
@ZapAnton Good catch! Yes, I'd missed the origin of that particular text. @xakon please disregard my previous; we can handle this within this repo. Steps to finish this:

1. Update [`config/exercise_readme.go.tmpl`](https://github.com/exercism/rust/blob/master/config/exercise_readme.go.tmpl) to fix the typos in the template.
2. Ensure `bin/configlet` exists; if not, run `bin/fetch-configlet` to get it.
2. Run `bin/configlet generate .` from the project root to regenerate all exercise readmes to fix the issue everywhere.

**Comment by xakon** [comment]
Hello!

Yes, @coriolinus, I would happily make a PR to the [problem specification repo](https://github.com/exercism/problem-specifications/).  I didn't know in the beginning how the whole process is being set, my apologies on that.  On the other hand, it is a good opportunity for me to get introduced to it!

**Comment by xakon** [comment]
Based on the instructions of @coriolinus, I updated the template `README`.  As a result, the typos are propagated to all exercises.  Unfortunately, the PR has become huge now!

**Pull request merged**
