### PR TITLE
Fix assert's result that's unexpected.

### PR DESCRIPTION
**Pull request by Jerrody**

### CODE REVIEW

**Comment by coriolinus** [comment]
As you can see, this causes the example solution to fail in CI, while it passes in CI with the existing solution. Could you explain why you think this test needs changing?

**Comment by Jerrody** [comment]
> As you can see, this causes the example solution to fail in CI, while it passes in CI with the existing solution. Could you explain why you think this test needs changing?

That's because I cannot understand that test_cast_spell_with_enough_mana ->100 - 3 = 97. But not **6**.

**Comment by petertseng** [comment]
Take a look at the instructions to see what `cast_spell` should return.

**Comment by Jerrody** [comment]
> 
> 
> Take a look at the instructions to see what `cast_spell` should return.

Oh, my bad. Didn't read this until the end.

**Pull request closed without merging**
