### PR TITLE
Update test allergies.rs

### PR DESCRIPTION
**Pull request by luigimassa**
Error total Allergies

### CODE REVIEW

**Comment by petertseng** [comment]
that would not be correct, and we cannot approve this. they are not allergic to strawberries, so we must not add 8.

**Comment by luigimassa** [comment]
please, check the test:
`#[test]
#[ignore]
fn is_allergic_to_egg_shellfish_and_strawberries() {
    let allergies = Allergies::new(5);
    assert!(allergies.is_allergic_to(&Allergen::Eggs));
    assert!(allergies.is_allergic_to(&Allergen::Shellfish));
    assert!(!allergies.is_allergic_to(&Allergen::Strawberries));
}`
Eggs + Shellfish + Strawberries = 13 not 5

**Comment by petertseng** [comment]
Not allergic to strawberries, so only eggs and shellfish get added.

**Comment by petertseng** [comment]
The test name is wrong though. Let's correct the test name.

**Pull request merged**
