### PR TITLE
Add more tests to the `bob` exercise

### PR DESCRIPTION
**Pull request by vvv**
Tests are copied from the Haskell language track:
https://github.com/exercism/haskell/blob/master/exercises/bob/test/Tests.hs

### CODE REVIEW

**Comment by IanWhitney** [comment]
Looks like these tests are also in the the official suite

https://github.com/exercism/problem-specifications/blob/3833e0554f890fa40c774e1bfd79023542638d4f/exercises/bob/canonical-data.json

**Comment by vvv** [comment]
@IanWhitney: Nice! I was unaware of “problem-specifications” repository.

Should I rewrite the tests (bob/tests/bob.rs)?

**Comment by IanWhitney** [comment]
We do like it if our test suite matches the official suite, so if you want to tackle that then I say 👍

**Comment by petertseng** [comment]
If doing that, then https://github.com/exercism/rust/blob/master/exercises/bob/Cargo.toml#L3 may be updated to match the problem-specifications version. That version is used to track what version of problem-specifications we are compliant with. It's currently 0.0.0 so we are not in compliance with any problem-specifications version.

**Comment by vvv** [comment]
@petertseng Got it, thank you.

**Comment by vvv** [comment]
Abandoned in favour of #312, which is rebased.

**Pull request closed without merging**
