### PR TITLE
README updates from problem-specifications

### PR DESCRIPTION
**Pull request by petertseng**
individual commit messages (properly attributed to original authors) explain

these commits should not be squashed when merging

### CODE REVIEW

**Review by coriolinus — APPROVED** [review]

**Comment by petertseng** [comment]
@iHiD , could you enable merge commits for this repository, please? These commits don't really make sense to squash (they all deserve their own individual explanation and attribution to original authors), so I would really like to make a merge commit. Right now it says "not enabled for this branch")

(If I can help provide a reminder, I remember that when you did this for a different track at https://github.com/exercism/haskell/pull/911#issuecomment-617087789, you needed to disable the branch protection for "Require linear history")

**Comment by iHiD** [comment]
@petertseng They're already enabled for this repo. To access them, you can use the arrow to the Right of "Squash and merge": 
Screenshot 2020-10-10 at 14 46 50

Please let me know if that doesn't work for you.

**Comment by petertseng** [comment]
"Not enabled for this branch". 
not-enabled

**Comment by petertseng** [comment]
@iHiD I am very sorry, I should have said "enable for this branch" instead of "enable for this repo". Here is what happens when I click the arrow. You will see it says "Not enabled for this branch". Could we have it enabled, please?

not-enabled

**Comment by iHiD** [comment]
Sorry - I should have followed your link. I've disabled the linear history guard, so it should hopefully work now.

**Comment by petertseng** [comment]
(As can be seen) It does work now, thank you!

**Pull request merged**
