### PR TITLE
pascals-triangle: Added tests and more README info.

### PR DESCRIPTION
**Pull request by hekrause**
While working at this exercise a few days before i thought there should be tests for higher row requests.

I noticed also that the prototype of the *rows* where where given with a **Vec<Vec<**u32**>>** parameter so that at some point the values in the middle should exceed the u32-type-boundaries and a test should panic.

To better understand the principle of the pascals triangle i added another line in the README.

### CODE REVIEW

**Comment by petertseng** [comment]
Need to ask a favour: For you to submit this pull request to https://github.com/exercism/problem-specifications/blob/master/exercises/pascals-triangle/canonical-data.json and https://github.com/exercism/problem-specifications/blob/master/exercises/pascals-triangle/description.md. If you do not, then when the Rust track uses those files to create its README and tests, these changes you've made will be overwritten and lost. We wouldn't want that to happen.

**Comment by petertseng** [comment]
When you make that pull request, I advise that it will be good to prepare a reason for why the following quote from https://github.com/exercism/problem-specifications/pull/362 should be reconsidered:

> Fewer Tests
>
> Once a student has gotten 4 rows to work the probably have the algorithm down. No real reason to test larger numbers that I can see.

**Comment by petertseng** [comment]
I needed to add the exercise name to the PR title, otherwise when I look at https://github.com/exercism/rust/pulls I have no idea what this PR is for. Please do this in future PRs

**Comment by hekrause** [comment]
@petertseng I made the requested pull request.([here](https://github.com/exercism/problem-specifications/pull/963))

**Comment by petertseng** [comment]
Reminder to review this now that the problem-specifications PR is merged.

The version in Cargo.toml should now be 1.2.0

**Comment by petertseng** [comment]
Very good, thank you.

**Pull request merged**
