### PR TITLE
exercise_readme: fix broken link to modules docs

### PR DESCRIPTION
**Pull request by stringparser**
The original link was renamed.

### CODE REVIEW

**Comment by coriolinus** [comment]
That's a good spot and a good fix, but the fix is applied in the wrong place.

Rust's README files are all based on a [template file](https://github.com/exercism/rust/blob/master/config/exercise_readme.go.tmpl), which contains that link. What you'll need to do is update that template, then use configlet (`bin/fetch-configlet`) to regenerate the documentation for every exercise, like:

```sh
bin/configlet generate . 
```

That will update everything in a way that will make Travis happy.

**Comment by stringparser** [comment]
I see! Updated the template and fetched the configlet. 

There is some error shown by `bin/configlet generate .` though

```sh
 ➜  rust (master) ✔ bin/configlet generate .
-> path not found: /Users/stringparser/code/problem-specifications
```

**Comment by coriolinus** [comment]
Oops, forgot configlet didn't do that for you. You need to fetch the problem specifications repo also. Simplest way, from within the rust repo:

```sh
git clone git@github.com:exercism/problem-specifications.git ../problem-specifications
```

**Comment by stringparser** [comment]
Ok, done. Let's see what travis says 👍 👎

**Comment by petertseng** [comment]
guess we were only out of date on anagram and bob. we really should put those into their own commits though. did that. please do not squash when merging

**Comment by petertseng** [comment]
since this is no longer about just hello-world only, hello-world should be removed from commit message and PR title

**Pull request merged**
