### PR TITLE
Scale generator README fixes

### PR DESCRIPTION
**Pull request by r4f4**
SSIA

### CODE REVIEW

**Comment by coriolinus** [comment]
Thanks for contributing this!

The CI failure is at least partially not your fault; see https://github.com/exercism/rust/pull/929 for details. You may need to rebase this PR once that one is merged. Still, CI will need to pass before we can consider merging.

I note that in several instances you have added trailing whitespace at the end of lines. This may or may not be your fault. If the trailing whitespace derives from the problem specifications, CI will mandate that we include it. If it's something you added, you'll need to remove it.

I haven't been tracking the state of the [upstream specifications repo](https://github.com/exercism/problem-specifications) very closely, so I'm not sure whether or not this PR is tracking changes made there. If it is not, then we won't be able to merge this until the changes are also made there: CI ensures that the README files stay synchronized with those specifications. If it is in fact tracking changes there, you'll also need to update the version field in `Cargo.toml` appropriately.

**Comment by r4f4** [comment]
> I note that in several instances you have added trailing whitespace at the end of lines. This may or may not be your fault. If the trailing whitespace derives from the problem specifications, CI will mandate that we include it. If it's something you added, you'll need to remove it.

The trailing whitespaces are there to create a new line. If there is a better way to do that, let me know.

> I haven't been tracking the state of the [upstream specifications repo](https://github.com/exercism/problem-specifications) very closely, so I'm not sure whether or not this PR is tracking changes made there. If it is not, then we won't be able to merge this until the changes are also made there: CI ensures that the README files stay synchronized with those specifications. If it is in fact tracking changes there, you'll also need to update the version field in `Cargo.toml` appropriately.

Oh I see. I'll send a PR against the problem-specifications repo then.

**Comment by coriolinus** [comment]
> If there is a better way to do that, let me know.

The better way depends on your intent. In these cases, I'd probably go with unordered lists, personally.

**Comment by r4f4** [comment]
I see issue https://github.com/exercism/problem-specifications/issues/1640 is already tracking the formatting and I created https://github.com/exercism/problem-specifications/issues/1642 for the typo. I'm closing this PR.

**Comment by coriolinus** [comment]
Oh, very good. Thanks for putting in this work!

**Pull request closed without merging**
