### PR TITLE
step down as a maintainer

### PR DESCRIPTION
**Pull request by efx**
I need to divert my free cycles to personal life.

### CODE REVIEW

**Comment by iHiD** [comment]
You shall be missed and I strongly hope we have you back at some point. Enjoy the redirected cycles 💙

**Comment by SleeplessByte** [comment]
👋🏽 see you when we see you 👋🏽

**Comment by BethanyG** [comment]
Thank you for all you've done here.  💜   I've really enjoyed interacting with you. 😄   May all go great until we meet (I hope!) again. 🌟 👋🏽

**Review by coriolinus — APPROVED** [review]
Best of luck moving forward!

**Comment by taiyab** [comment]
You will be missed.

**Comment by ErikSchierboom** [comment]
Thanks for everything @efx!

**Comment by efx** [comment]
@iHiD @coriolinus @SleeplessByte @BethanyG @taiyab @ErikSchierboom thank you each for the kind and thoughtful words!

**Comment by efx** [comment]
@ErikSchierboom or @iHiD do one of you have the power to approve? I would appreciate it so I can merge. Thanks!

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@efx Done!

**Pull request merged**
