### PR TITLE
macros: Add new tests to check for invalid syntax

### PR DESCRIPTION
**Pull request by pedantic79**
- Use the trybuild crate for additional tests.
- These tests contain invalid syntax, and are designed not to compile.
- Student macros should produce an error instead of compile.

### CODE REVIEW

**Comment by pedantic79** [comment]
Looks like this only works with: `Compiler support: requires rustc 1.36+`

If you remove the `*.stderr` file it gives you this:
```
test tests/invalid/double-commas.rs ... wip

NOTE: writing the following output to `wip/double-commas.stderr`.
Move this file to `tests/invalid/double-commas.stderr` to accept it as correct.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error: no rules expected the token `,`
 --> $DIR/double-commas.rs:5:24
  |
5 |     hashmap!('a' => 2, ,);
  |                        ^ no rules expected this token in macro call
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```

**Comment by pedantic79** [comment]
I'm a little in different about this as well. An alternative to `trybuild` seems to be [`compiletest-rs`](https://github.com/laumann/compiletest-rs).

**Comment by pedantic79** [comment]
We should probably update the `README.md` with something that explains the limitations:
1. `rustc --version` reports 1.36 or higher, also linking to instructions on how to update stable toolchain
2. what to do if it fails with a different error message. i.e. a `mismatch` occurs. Maybe compile with `TRYBUILD=overwrite` and report it. Although supporting different error messages from different compilers would be a huge hassle.

**Comment by coriolinus** [comment]
Agree with point 1. Point 2, if the implementation is correct but the error message mismatches, they should report it as an issue in this repo.

**Comment by workingjubilee** [comment]
Note that while the trybuild crate is not in `rustc`, it uses a similar implementation as the `rustc` test suite for exactly these kinds of errors (UI errors are hard to test for!).

**Comment by DevinR528** [comment]
I wonder if this would be helpful also [macrotest](https://github.com/eupn/macrotest)?

**Comment by coriolinus** [comment]
I do not feel strongly about `trybuild` vs `compiletest-rs`. If @pedantic79 wants to switch implementations, that is fine. If not, that is also fine, IMO.

It looks to me like `macrotest` is intended to verify specific macro expansions. We don't want to do that here; we want students to have maximum implementation flexibility.

**Comment by coriolinus** [comment]
Oh, regarding the minimum supported `rustc` version: in general, we allow `example.rs` to depend on features from the latest stable rust version. Given that the minimum supported version is now six versions old, I don't believe a note is required.

**Comment by pedantic79** [comment]
@coriolinus I added the commit just to see what you thought. I can revert it.

**Comment by coriolinus** [comment]
I don't object to the comment, but you need to [update `hints.md`](https://github.com/exercism/rust/blob/master/README.md#on-modifying-the-exercises-readme) for CI to be happy about it.

**Comment by pedantic79** [comment]
@coriolinus thanks

**Comment by pedantic79** [comment]
So we may have a problem with this.

This solution:
```rust
#[macro_export]
macro_rules! hashmap {
    ( $($key:expr => $value:expr),* $(,)? ) =>  {
        {
            let mut _m = ::std::collections::HashMap::new();
            $(_m.insert($key, $value);)*
            _m
        }
    };
}
```

Gives different compiler error messages for:
```
hashmap!(, 'a' => 2);
```
and
```
hashmap!(,);
```

Not sure how to handle this with `trybuild`

**Comment by pedantic79** [comment]
If we remove the `*.stderr` files, then for passed tests we get this:

```
test tests/invalid/leading-comma.rs ... wip

NOTE: writing the following output to `wip/leading-comma.stderr`.
Move this file to `tests/invalid/leading-comma.stderr` to accept it as correct.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error: no rules expected the token `,`
 --> $DIR/leading-comma.rs:5:14
  |
5 |     hashmap!(, 'a' => 2);
  |              ^ no rules expected this token in macro call
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```

**Comment by coriolinus** [comment]
I've put in a feature request to suit our use case: https://github.com/dtolnay/trybuild/issues/56. It looks like the maintainer is very active, so I'm willing to wait until they get back.

In the meantime, I am going to put on hold the plans to merge this. Ideally, we can get a new `trybuild` version out shortly which better suits our use case.

**Comment by pedantic79** [comment]
I have a patch, which sets  the environment variable `TRYBUILD=overwrite`. This causes it to write out a new stderr if it doesn't match. 
--
Using `example.rs` the output looks like this:
```
test tests/invalid/comma-sep.rs ... ok
test tests/invalid/double-commas.rs ... ok
test tests/invalid/leading-comma.rs ... ok
test tests/invalid/only-arrow.rs ... ok
test tests/invalid/only-comma.rs ... ok
test tests/invalid/single-argument.rs ... ok
test tests/invalid/triple-arguments.rs ... ok
test tests/invalid/two-arrows.rs ... ok
```
--
Using this [student solution](https://exercism.io/mentor/solutions/80240c6472fd40f4a6ae5924e2bd0f33):
```
test tests/invalid/comma-sep.rs ... ok
test tests/invalid/double-commas.rs ... ok
test tests/invalid/leading-comma.rs ... wip

NOTE: writing the following output to `tests/invalid/leading-comma.stderr`.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error: no rules expected the token `'a'`
 --> $DIR/leading-comma.rs:5:16
  |
5 |     hashmap!(, 'a' => 2);
  |                ^^^ no rules expected this token in macro call
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

test tests/invalid/only-arrow.rs ... ok
test tests/invalid/only-comma.rs ... wip

NOTE: writing the following output to `tests/invalid/only-comma.stderr`.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0282]: type annotations needed for `std::collections::HashMap<K, V>`
 --> $DIR/only-comma.rs:5:5
  |
5 |     hashmap!(,);
  |     ^^^^^^^^^^^^
  |     |
  |     consider giving `temp_map` the explicit type `std::collections::HashMap<K, V>`, where the type parameter `K` is specified
  |     cannot infer type for type parameter `K`
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

test tests/invalid/single-argument.rs ... ok
test tests/invalid/triple-arguments.rs ... ok
test tests/invalid/two-arrows.rs ... ok


test test_invalid_syntax ... ok
```
--
This [student solution](https://exercism.io/mentor/solutions/644c98b29f7041a5a46b26f093b26263) (once corrected to compile) shows that it allows `hashmap!('a'=>1, ,)`

```
test tests/invalid/comma-sep.rs ... ok
test tests/invalid/double-commas.rs ... error
Expected test case to fail to compile, but it succeeded.

test tests/invalid/leading-comma.rs ... ok
test tests/invalid/only-arrow.rs ... ok
test tests/invalid/only-comma.rs ... ok
test tests/invalid/single-argument.rs ... ok
test tests/invalid/triple-arguments.rs ... ok
test tests/invalid/two-arrows.rs ... ok


test test_invalid_syntax ... FAILED

failures:

---- test_invalid_syntax stdout ----
Setting TRYBUILD
thread 'test_invalid_syntax' panicked at '1 of 8 tests failed', /Users/dnn/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.24/src/run.rs:60:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test_invalid_syntax' panicked at 'assertion failed: result.is_ok()', tests/macros.rs:101:5
```

**Comment by pedantic79** [comment]
Add a commit that sets the `TRYBUILD` environment variable to `overwrite` just before running the tests. This gives us better behavior. But still not ideal.

**Comment by coriolinus** [comment]
Agree it's not ideal, but since https://github.com/dtolnay/trybuild/pull/57#pullrequestreview-383342617, this seems as close as we're going to get. @pedantic79 do you feel there's more work to be done here, or would you like to have this merged now?

**Comment by pedantic79** [comment]
@coriolinus Let's wait until Friday. I would like to see how hard it would be to try to implement a stripped down `trybuild`.

**Comment by pedantic79** [comment]
@coriolinus Please look at #933, it's not as robust as `trybuild` but hopefully enough functionality for our students.

**Comment by coriolinus** [comment]
Closing in favor of #933. I agree, that looks like the better approach.

**Pull request closed without merging**
