### PR TITLE
fix clippy beta lints

### PR DESCRIPTION
**Pull request by coriolinus**
Fix lints introduced in the new Rust 1.53-beta.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@coriolinus Let me know if you want me to approve, should Peter Tseng not have the time to review.

**Comment by coriolinus** [comment]
@ErikSchierboom if you have time, that'd be great. I know you also have other priorities, which is why I didn't tag you.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@coriolinus Feel free to tag me! If I'm too busy, I'll just be slow to respond :)

**Comment by petertseng** [comment]
Very interesting (and good!) that clippy checks for assert_eq with bools now!

**Pull request merged**
