### PR TITLE
Concept Exercise: Bird Watcher

### PR DESCRIPTION
**Pull request by saurabhmishra-io**
Implementation of the issue I raised: https://github.com/exercism/rust/issues/1585#issue-1439299114

Exemplar solution may not be idiomatic. 

Please provide suggestions if any.

### CODE REVIEW

**Comment by saurabhmshr** [comment]
Hi @bobahop / @petertseng can you provide me feedback for this PR ?

**Comment by bobahop** [comment]
Thanks for contributing! I'm sorry, but I won't be able to get to this anytime soon.

**Comment by saurabhmshr** [comment]
Sure @bobahop . Do you think its a good idea for me to create PRs based on exercises that exist in other tracks (Go, Python, Java) but not Rust ?

**Comment by bobahop** [comment]
@saurabhmshr Sure, it's fine to transpose an exercise from one language to another, making sure to credit the original author in the config.json. Also, when doing so, the [problem-specifications repository](https://github.com/exercism/problem-specifications) should be used if the exercise is defined there. For bird watcher, it apparently is not.

**Pull request closed without merging**
