### PR TITLE
simple-cipher: Update Cargo.toml to use rand 0.8

### PR DESCRIPTION
**Pull request by GreenPenguino**
Update to use a more recent version of `rand`

### CODE REVIEW

**Review by coriolinus — APPROVED** [review]
Looks good, thanks!

**Comment by coriolinus** [comment]
Oops, jumped the gun a little. Looks like `rand` had a breaking change in their API at some point; you'll need to update the example solution such that CI is green. Once that's set, this should be mergeable.

**Comment by GreenPenguino** [comment]
@coriolinus how to restart the CI checks?

**Comment by coriolinus** [comment]
CI starts automatically once you have a commit merged into the repo. I started it for you; as you can see, it works now. Thanks for doing this work!

**Pull request merged**
