### PR TITLE
🤖 Flatten authors and contributors in .meta/config.json files

### PR DESCRIPTION
**Pull request by ErikSchierboom**
The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.

We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 

See https://github.com/exercism/docs/pull/90/files

## Automatic Merging

We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.

## Tracking

https://github.com/exercism/v3-launch/issues/26

### CODE REVIEW

**Review by coriolinus — APPROVED** [review]
Simplifying to github username was a good idea.

[edit]: This is going to break our CI until such time as `configlet` is updated with the new lint rules, so please refrain from merging until the new `configlet` is about ready to release.

**Review by iHiD — COMMENTED** [review]
We are now merging this PR automatically to help prepare your track for Exercism v3.

**Comment by ErikSchierboom** [comment]
@coriolinus We're building a new release of configlet right now. Should be there in 15-30 minutes.

**Comment by iHiD** [comment]
(for clarity - my comment was automated 🙂)

**Comment by ErikSchierboom** [comment]
@coriolinus configlet has been updated and I restarted the job. It is green now :) Feel free to merge this once the other checks are green.

**Review by efx — APPROVED** [review]

**Comment by efx** [comment]
Given this is approved I will merge since I merged two other PRs that are failing on main.

**Comment by efx** [comment]
In general, I believe Rust maintainers defer to the contributor or initiating maintainer to self-merge.

**Pull request merged**
