### PR TITLE
gigasecond:add clarity to exercise goal

### PR DESCRIPTION
**Pull request by andy5995**
This helps address my comments in
https://github.com/exercism/rust/pull/710#issuecomment-438078198

### CODE REVIEW

**Comment by andy5995** [comment]
Hmm.. failed 4/5 travis tests. Not sure why.

**Comment by ZapAnton** [comment]
Travis has failed, because you modified the part of the README, that comes from the problem-specifications repo.

[This section](https://github.com/exercism/rust#on-modifying-the-exercises-readme) explains the problem.

**Comment by andy5995** [comment]
@ZapAnton thanks for explaining. Is the change I suggested desired? If so, I'll modify the appropriate file in the other repo.

**Comment by coriolinus** [comment]
The change you made here looks plausible to me, though there are a lot more moderators in the problem-specifications repo than there are here.

**Comment by andy5995** [comment]
Submitted to the [problem-specifications repo](https://github.com/exercism/problem-specifications/pull/1398)

**Comment by coriolinus** [comment]
Great! As soon as it's merged there, we can rerun Travis here, which should
then pass.

**Comment by petertseng** [comment]
Well, as you've now seen, that's what happens sometimes with problem-specifications. But this is a natural part of everyone wanting what's best for their track.

Now updated with the final version that resulted in problem-specifications, which means let's merge it.

**Pull request merged**
