### PR TITLE
Add test case to rust/anagram to prevent ascii-sum-solutions

### PR DESCRIPTION
**Pull request by apanloco**
Prevent solutions that use the sum of the ascii values of each char
to find anagrams.

### CODE REVIEW

**Review by coriolinus — APPROVED** [review]
I'd be startled to see an implementation which passed all other tests but failed this, but this test makes it absolutely clear that summing over ascii values is an improper strategy. Have you considered also upstreaming this test case to https://github.com/exercism/problem-specifications/?

**Comment by apanloco** [comment]
This implementation fails only this :)
https://exercism.io/tracks/rust/exercises/anagram/solutions/4ceb938349304e4cbb081f1cd2c20775

**Comment by apanloco** [comment]
no, i haven't considered doing that... I'll look into it.

**Comment by bobahop** [comment]
If you do the upstreaming, make sure you use a version 4 UUID. I got bit on that one before.

**Pull request merged**
