### PR TITLE
track: Migrated the existing exercises to the Rust 2018 edition

### PR DESCRIPTION
**Pull request by ZapAnton**
This PR shows what simple migration to the 2018 edition would look, when `cargo fix` is applied to every exercise on the track.

Since the changes were nor discussed nor approved by the maintainers , this PR serves as a demonstration of the migration, and should be closed, if the changes are not desirable.

A script, that was used for the migration:

```bash
#!/usr/bin/env bash                                                                                                                               
                                                                                                                                                  
for dir in exercises/*/; do                                                                                                                       
    (                                                                                                                                             
        cd $dir                                                                                                                                   
                                                                                                                                                  
        sed -i '2iedition = "2018"' Cargo.toml                                                                                                    
                                                                                                                                                  
        cargo fix --edition-idioms --allow-dirty                                                                                                  
                                                                                                                                                  
        cargo fmt                                                                                                                                 
                                                                                                                                                  
        cargo clean                                                                                                                               
    )                                                                                                                                             
done    
```

### CODE REVIEW

**Comment by ZapAnton** [comment]
Done

**Comment by ZapAnton** [comment]
The build failed for several reasons:
- The READMEs for some exercises are not up-to-date. Since https://github.com/exercism/rust/pull/771 was merge the rebase will solve this.
- Some deprecated exercises (namely `hexadecimal` and `hexadecimal`) were modified and included in the Travis check. Since they are deprecated and do not even have a stub file, they could be ignored.
- `dominoes` and `reverse-string` have some actual error in them. Will investigate further

**Comment by ZapAnton** [comment]
> Some deprecated exercises (namely nucleotide-codons and hexadecimal) were modified and included in the Travis check.

Actually that raises a question - should deprecated exercises be present on the track? Maybe they could be removed, so not to complicate Travis scripts?

**Comment by coriolinus** [comment]
Agree that deprecated exercises could be removed.

**Comment by ZapAnton** [comment]
OK, now Travis has failed only because of the deprecated exercises. To make it pass I would have to rebase against https://github.com/exercism/rust/pull/773

**Comment by petertseng** [comment]
Note: dfdb48f1a1fadf0946756b54950f69cea7859cc0 should be good

**Comment by petertseng** [comment]
Trying with just the edition and `use` path changes to see what's *required* to build

**Comment by petertseng** [comment]
Okay, that build succeeded, so only the `use` path changes are required. Will leave notes in commit messages explaining that.

**Comment by petertseng** [comment]
Other changes I made to support this PR:

* https://github.com/exercism/rust/pull/779
* Add `edition` to all the Cargo-example.toml as well
* Apply the `use crate::` to `scale-generator` and `poker` as well, where they were needed. Commit https://github.com/exercism/rust/pull/769/commits/9dad928afbc9cb1f6802d5e9fe1da50db652881b

**Pull request merged**
