### PR TITLE
[v3] Update Practice Exercises to latest spec

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This week we've defined what the file structure looks like for Practice Exercises. Please skim through [this docs PR](https://github.com/exercism/docs/pull/36#issue-566737871) that gives an overview of the changes, and see [the spec](https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md) for more information.

This PR applies changes to the track to conform to the latest spec. Each change is made as a separate commit, to help with reviewing. When merging this PR, I would suggest to _not_ squash this to preserve the individual commits.

As having this PR merged is essential to prepare this track for Exercism v3, we'll automatically merge this PR one week after it was opened (if it hasn't been merged already).

Here are the changes made:

## Add practices field to Practice Exercises

While working on adding prerequisites to the Practice Exercises, we found that we really need two keys for Practice Exercises:

- `practices`: Concepts that the Practice Exercise is actively helping a student to practice. These show up in the UI as "Practice this Concept in: TwoFer, Leap, etc`
- `prerequisites`: The actual Concepts that should have been learnt by a student in order for them be able to do that Exercise.

There are lots of advantages to having the two keys instead of using one key for two purposes, not least that having them split out gives the maintainers a lot more control over the order a student should be exposed to exercises (via the prerequisites) and also where they encourage them to try concepts (via practices), which in reality are quite different things.

We have updated [the docs](https://github.com/exercism/docs/blob/master/anatomy/tracks/practice-exercises.md#practices) with more details and explanation on this.

## Remove README.md files

v3 Practice Exercises won't have a (generated) README.md file anymore. This file will be replaced by `.docs/instructions.md` and optionally a `.docs/introduction.md` files. These files are copies of the information defined for their corresponding problem-specifications exercise (if any).

Exercism v3 will build the README.md file that is sent via the CLI from these files contents, along with some other files.
See [this document](https://github.com/exercism/docs/blob/main/anatomy/tracks/presentation.md) for more information.

This PR removes the `README.md` files.

## Create instruction from prob-specs descriptions

The `.docs/instructions.md` file is a copy of the `instructions.md` file of the problem-specifications exercise, or if that does not exists, its `description.md` file.

The new [configlet](https://github.com/exercism/configlet) version will add support for doing this syncing automatically.

This PR adds the `.docs/instructions.md` file from the problem-specifications exercise's `description.md` file.

## Move .meta/hints.md to .docs/instructions.append.md

As noted above, v3 Practice Exercises will have a `.docs/instructions.md` and optionally a `.docs/introduction.md` file. 

To add track-specific contents to the instructions and/or introduction, exercises can define the (optional) `introduction.append.md` and `instructions.append.md` files. If present, the contents of these files will automatically be append to their corresponding file when generating the README.md

This PR renames any `.meta/hints.md` files to `.docs/instructions.append.md`.

## Create .meta/config.json files

Practice Exercises in Exercism v3 will have a `.meta/config.json` file that contains exercise-specific information like the names of the solution, test and example file(s).

The `.meta/config.json` file will also contain any source information as defined for the corresponding problem-specifications exercise (if any).

This PR adds the `.meta/config.json` file.

The contents of this file are temporary, and we'll submit follow-up PRs to update their values:

1. The authors and contributors will be inferred from the Exercise's git history.
2. As the Exercise files for most tracks are very regular, we're working on a solution that will allow you to define the pattern in your tracks's `config.json` file, and then use [configlet](https://github.com/exercism/configlet) to generate the contents of the `files` property in the exercise's `.meta/config.json` file based on the track-defined pattern.

## Tracking

https://github.com/exercism/v3-launch/issues/16

### CODE REVIEW

**Comment by efx** [comment]
Cursory read looks OK to me. I will approve on passing CI. 
It looks like configlet fails because our concept exercises in `main` are not well-formed. I'm guessing because this PR bumps configlet?
Either way I'll submit other PRs to address those.

**Comment by ErikSchierboom** [comment]
> I'm guessing because this PR bumps configlet?

Close. There was a new configlet release and the CI will always work with the latest configlet.

**Comment by coriolinus** [comment]
Don't merge yet please, I'm currently running a script so this will include
at least basic authorship information for each practice exercise.

**Comment by ErikSchierboom** [comment]
> Don't merge yet please, I'm currently running a script so this will include
at least basic authorship information for each practice exercise.

I'm planning to do this next week :) I'll also add contributors, but feel free to do an initial pass. That was we can see if there any differences and why. If you don't mind, could you share how you're determining the authors?

**Comment by coriolinus** [comment]
In short: use the git history to find the initial commit for the exercise. Use the github API to find the first pull request mentioning that commit. Choose the github username of the person who opened the pull request as the author.

I'll share the script around once it works the way I want it to.

**Comment by ErikSchierboom** [comment]
Excellent, thanks!

**Review by coriolinus — APPROVED** [review]
Looks good. Will look forward to the additional tooling filling out things like practice exercises' files.

**Comment by ErikSchierboom** [comment]
Thanks for the review and the pre-filling of the authors!

**Pull request merged**
