### PR TITLE
sum-of-multiples: Removed a duplicated sentence in README

### PR DESCRIPTION
**Pull request by GoneUp**
Basically what the title says. I stumbled across the duplicated sentence while doing the exercises.

### CODE REVIEW

**Comment by GoneUp** [comment]
Ah, okay. I didn't know that all tracks have (at least partly) the same description. I will do that tomorrow.

**Comment by ijanos** [comment]
Thank you! I'm closing this one now, if you don't mind.

**Comment by petertseng** [comment]
OK, it got merged in problem-specifications.

**Comment by petertseng** [comment]
(I need to change "Removed" to "Remove" - commit messages are imperative)

Thanks for your contribution.

**Pull request merged**
