### PR TITLE
link to TRPL example

### PR DESCRIPTION
**Pull request by efx**
I was not planning on any further work on this concept now, but I did research the topic a bit today and found this description helpful.
Instead of trusting my inconsistent note-taking, `concepts/` it is!

### CODE REVIEW

**Comment by efx** [comment]
Failure is a new configlet lint:
> Not a valid tag: "platform/wasm":
> exercism/rust/config.json

I'll fix that in this PR.

**Comment by ee7** [comment]
I saw:

> Not a valid tag: "platform/wasm":
> exercism/rust/config.json

But `platform/wasm` might be a good tag. I've asked about whether we should add it.

**Review by coriolinus — APPROVED** [review]

**Comment by efx** [comment]
Shall we:
1. merge PR's that only fail because of this tag?
1. remove the tag for now and create an issue to follow up?

I prefer #2 so I have less to keep track of LOL.

**Comment by coriolinus** [comment]
Option 2 works for me.

**Pull request merged**
