### PR TITLE
all-your-base: Fixing test: Empty slice corresponds to zero

### PR DESCRIPTION
**Pull request by CGMossa**
In the template code, it says
```
> /// Notes:
> ///  * The empty slice ( "[]" ) is equal to the number 0.
```
But this test assumes that the empty slice should yield an empty slice, and not zero as noted here.

### CODE REVIEW

**Comment by coriolinus** [comment]
Thank you @CGMossa for making this change! I agree, this improves the exercise.

You will also need to update `example.rs` so that the example demonstrates this new behavior. Once you have done so, Travis will pass. Once that is done, I will approve this.

**Comment by petertseng** [comment]
In addition to the necessary code changes to example.rs, in src/lib.rs the sentence stating `Never output leading 0 digits.` will have to be changed to something like "Render the value 0 as [0]. Never output leading 0 digits in any other case.", otherwise it would no longer be consistent with the tests.

**Comment by workingjubilee** [comment]
Looks like this would still be good with those followup changes, no merge conflicts.

**Comment by coriolinus** [comment]
Closing due to inactivity.

**Comment by CGMossa** [comment]
Sorry, I have completely forgotten about this. If there is something you know I can do or something, please send me a message.

**Comment by workingjubilee** [comment]
Hello, while I am leaving this closed for now, all you need to do is fix the problems cited by the other maintainer's comments and then this PR can be accepted!

> You will also need to update `example.rs`...

> In addition to the necessary code changes to example.rs, in src/lib.rs...

**Pull request closed without merging**
