### PR TITLE
[v3] Move Practice Exercise example files to .meta directory

### PR DESCRIPTION
**Pull request by ErikSchierboom**
The example implementation files for Practice Exercises should be located in the `.meta` directory. Besides being consistent with Concept Exercises, it also has the added benefit that no extra configuration is needed to prevent the example file from being downloaded to the student (as files in the `.meta` directory are never downloaded).

See [the spec](https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#file-example-implementation).

This PR attempts to detect these example files and move them to the exercise's `.meta` directory.

Note that this change will likely break your CI, so feel free to either merge this and fix the build later, or push a fix to this PR.  

## Tracking

https://github.com/exercism/v3-launch/issues/18

### CODE REVIEW

**Comment by efx** [comment]
>  or push a fix to this PR.

We prefer this approach. I can take a look sometime today.

**Comment by ErikSchierboom** [comment]
@efx I'm sorry, I'm pushing an update to this branch in a sec. I forgot to update the .meta/config.json files

**Comment by efx** [comment]
The CI [failure](https://github.com/exercism/rust/pull/1125/checks?check_run_id=1871025866#step:5:1) occurs because:
https://github.com/exercism/rust/blob/50aa0a1d2c98e6e7c7c48658cd49fee06ae6b4e7/bin/test-exercise#L62-L70
expects `example.rs` in the legacy location. Patching lines 63-64 to use `.meta/` will fix it.

**Comment by efx** [comment]
@ErikSchierboom were you going to update this branch some more or can I take it from here :) ?

**Comment by ErikSchierboom** [comment]
@efx No I am done. I added the commit that I wanted so be my guest!

**Comment by efx** [comment]
This is almost ready to be merged. The clippy failures should be resolved by #1150. 

Once we figure out the best approach for #1150 I'll merge main and approve.

**Review by efx — APPROVED** [review]
I wonder if we need the respective `.meta/config.json` changes, but figure its fine to leave them.

**Review by coriolinus — APPROVED** [review]

**Pull request merged**
