### PR TITLE
Changed `unimplemented!` calls to `todo!`

### PR DESCRIPTION
**Pull request by felix91gr**
Solves #1598

### CODE REVIEW

**Comment by Sjoeborg** [comment]
rip

**Comment by senekor** [comment]
Hey, sorry for the long wait :-)

I agree with the change. I guess the formatting needs to be fixed.

Also, there are some occurrences of "unimplemented" in markdown docs and shell scripts which should be adjusted accordingly, to make sure things stay consistent.

**Comment by senekor** [comment]
Oh and a reminder to whoever ends up merging this, we should definitely add `[no important files changed]` here. Although I'm not sure if the tests would even run if the source files are changed but not the test files. Better be safe.

**Comment by senekor** [comment]
superseded by https://github.com/exercism/rust/pull/1723

**Pull request closed without merging**
