### PR TITLE
check-exercises, ensure-stubs-compile, check-configlet-fmt.sh, check-exercise-crate.sh: Fixed the scripts to work on weekly builds

### LINKED ISSUE #758: check-exercises, ensure-stubs-compile: Make them run in the travis weekly (they currently don't)
We build the master branch in Travis to make sure everything is good.

We'd like that to test every exercise. This was the approach agreed upon in https://github.com/exercism/rust/pull/591#issuecomment-410188196 .

I present the most recent build of master, https://travis-ci.org/exercism/rust/jobs/455623555, where it says "No exercise was modified. The script is aborted."

Further, I present a build where I forced every exercise to be checked https://travis-ci.org/exercism/rust/jobs/456251504 for PR https://github.com/exercism/rust/pull/727

Note the errors

hexadecimal's stub does not compile; please make it compile or remove all non-commented lines
nucleotide-codons's stub does not compile; please make it compile or remove all non-commented lines
Exercises that don't compile:
hexadecimal
nucleotide-codons

These two pieces together tell us that Travis CI's master build does not check exercises. As noted above, it should.

---

the below information is irrelevant for this issue:

We build the master branch weekly instead of on every push to master, because https://github.com/exercism/discussions/issues/174#issuecomment-318855073 turned them off.
However, we do have the power to turn them back on if we so choose.
However, I think this detail is irrelevant to the issue at hand. No matter the mechanism of building master, it is currently the case that building master means no exercise is checked.

### PR DESCRIPTION
**Pull request by ZapAnton**
Closes #758

### CODE REVIEW

**Comment by ZapAnton** [comment]
I have used the one @petertseng provided in #758:
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

**Comment by ZapAnton** [comment]
Also [this post](https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/) helped a little

**Comment by coriolinus** [comment]
@ZapAnton Thanks! I just wanted to verify for myself that the docs claim that the variable is explicitly set to the value `false` when on `master`, because there's no obvious way to test this before merging. The docs do in fact say this, so I'm going to merge this now.

**Comment by petertseng** [comment]
I manually asked Travis to do https://travis-ci.org/exercism/rust/jobs/465899655 and it does look like it is doing all exercises as desired now, excellent!

So in a few minutes when it completes we should see that fails.

Haven't checked the weekly yet, but since the last one was 4 days ago we'd expect one in about 3 days.

**Pull request merged**
