### PR TITLE
adding links for Rust Recommended Learning Resources

### PR DESCRIPTION
**Pull request by gaurikholkar**
Adding a few links that helped me in the process of learning Rust

### CODE REVIEW

**Comment by ijanos** [comment]
Hi! Thank you for your contribution. I am not too fond of linking github repos with just a bunch of links. If a good resource is linked there then maybe we should link that directly. This week in rust is good, but I am not sure if it counts as a learning resource. 

I've checked a few other tracks and as I see they mainly link materials intended for beginners, but there is no consistency in the look of the pages. I think I would prefer if the resources page moved to a direction similar to the rust-learning repo. 

I'm going to think about this a little, in the meanwhile let's see if anybody else weighs in this topic and thank you again for the contribution.

**Comment by gaurikholkar** [comment]
@ijanos  sure. Let me know

**Comment by gaurikholkar** [comment]
Hi. any updates?

**Comment by petertseng** [comment]
Given that the description says "helped me in the process of learning Rust", now I am obligated to ask:

I understand RESOURCES to be for ongoing use, while LEARNING is for those who are learning. Does that affect which of the two files this should go in? Source: https://github.com/exercism/elixir/pull/91#issuecomment-175048631

Quote with Elixir changed to Rust:

> LEARNING is -- where you would start if you wanted to learn Rust from scratch, e.g. tutorials etc
> RESOURCES is -- where you would look stuff up if you were developing in Rust

Whichever file these links potentially go in, my opinion on them is that I have no strong reason to say yes or no. I'll go with what people think.

**Comment by gaurikholkar** [comment]
This one here
> LEARNING is -- where you would start if you wanted to learn Rust from scratch, e.g. tutorials etc
I'm still now sure on which links to proceed ahead with

**Comment by coriolinus** [comment]
In general I'm opposed to this change. "List of links" pages such as Awesome Rust are trivially googleable for the interested, and This Week in Rust is aimed more at people interested in the continued development of the language than people attempting to learn it.

It's been three months since this PR was opened, and I think it's time to resolve it one way or the other. I vote to close without merge. @petertseng last stated that he was neutral. @ijanos have you updated your opinion?

**Comment by ijanos** [comment]
I vote for closing without merge as well.

**Pull request closed without merging**
