### PR TITLE
 grep: Updated the exercise to 1.2.0 version

### PR DESCRIPTION
**Pull request by ZapAnton**
Adds 4 new test cases plus clippy suggestions.

Relevant PR: https://github.com/exercism/problem-specifications/pull/1356

### CODE REVIEW

**Comment by petertseng** [comment]
For PRs that follow problem-specifications, I would appreciate if you would link to the relevant problem-specifications PRs

**Comment by ZapAnton** [comment]
Could you elaborate a little in what form do you want a link - in the comment, in the commit message or merging the original commit like in 19b185a?

**Comment by petertseng** [comment]
Personally I think it would be good if they would be put in the commit message, because I think being able to find the source of something seems like a useful thing to keep in git history.

As for what form I'd like them, full URL (`https://github.com/exercism/problem-specifications/pull/1234`) seems fine, but I wonder if you have other ideas

**Comment by ZapAnton** [comment]
No other ideas, although there could be a problem with full URL, in case the linked repo is deprecated/renamed, but such case is exotic and is easily solved by the person, who looks up the link

**Comment by coriolinus** [comment]
I'm going to give this a day to give other maintainers the chance to chime in, but if nobody objects, I'm going to merge this tomorrow.

**Pull request merged**
