### PR TITLE
poker: example update

### PR DESCRIPTION
**Pull request by elektronaut0815**
Some little updates so the example works with the current versions of Rust and the Counter crate.

### CODE REVIEW

**Review by coriolinus — COMMENTED** [review]
Thanks for contributing this work!

Looks plausible in principle, but of course CI needs to pass before I can approve. Looks like the compiler doesn't like your use of `.collect::<Counter<_>>()` for some reason.

**Comment by coriolinus** [comment]
Oh--it's not really documented well, but the `FromIterator` implementation in `Counter` was added in v0.4.0; the `Cargo-example.toml` file still requires only v0.1.0. Fixing that should fix you up.

**Comment by elektronaut0815** [comment]
Now it's working.

**Review by coriolinus — APPROVED** [review]
Looks good, and thanks again!

**Comment by elektronaut0815** [comment]
Thanks for the exercise!

**Pull request merged**
