### PR TITLE
space-age: Update README.md

### PR DESCRIPTION
**Pull request by bobahop**
Suggest the use of a macro

### CODE REVIEW

**Comment by bobahop** [comment]
Occasionally a student will say they don't feel they are ready for macros, but often a student appreciatively says something like "I _knew_ there must be a better way to do it! Thanks!" and they submit an iteration using a macro.

**Comment by coriolinus** [comment]
CI is failing because you cannot just update README.md: that's a generated file. Instead, what you should do is:

- write the hint in `.meta/hints.md` (creating the file if necessary)
- get configlet (`rust/bin/fetch-configlet`)
- regenerate the readme: `configlet generate . -o anagram

I'll take a look later, when CI passes.

**Comment by coriolinus** [comment]
That said, I'm not convinced that a macro is actually the most elegant way to do this. These days, I'd lean towards a [const-based implementation](https://github.com/coriolinus/exercism-rs/blob/a5992dc9c9f9954f3aadee5a4d7744f83ab0cdab/space-age/src/lib.rs). You can save a tiny bit of boilerplate by adding a macro, bringing the impl-lines per planet from 3 to 1, but only at the cost of adding a non-trivial recursive macro. I'm not sure that tradeoff is worth it in this case.

**Comment by iago-lito** [comment]
I'd argue that "saving a bit of boilerplate" is not the only benefit of using macros here. Readability of the data counts, and I find the following much more comfortable to parse in [this kind](https://exercism.io/tracks/rust/exercises/space-age/solutions/04d5ad52fe984cc681bc8d79c4bdb1c0) of macro approach:
```rust
declare_planets! {
    Mercury:   0.2408467
      Venus:   0.61519726
      Earth:   1.0
       Mars:   1.8808158
    Jupiter:  11.862615
     Saturn:  29.447498
     Uranus:  84.016846
    Neptune: 164.79132
}
```
In particular, these solutions *can* also use associated consts.
Also, the boilerplate factorized by the macro is rather trivial, which makes it easy to understand and improves readability much. This is a canonical use-case for macros IMHO.

**Comment by coriolinus** [comment]
Good point. That macro is simpler and nicer than I'd expected; I'd imagined for some reason that we'd need a recursive deconstruction of the list, instead of just using the repetition operator. Consider me convinced that it's worth suggesting a macro.

**Comment by gilescope** [comment]
Agreed - all for hinting that a macro would save them time - it's a bit tedious without macros as exercises go. Without macros I could happily live in a solar system with only three planets in.

**Comment by bobahop** [comment]
Okay, I committed the local edits and pushed them to my fork on GH. Not sure how I can create a pull request for just the space-age files, as it did not create a separate branch for today's space-age changes. It looks like it wants to PR today's anagram file changes as well as today's space-age file changes if I do a pull request. I don't want to create a mess. Sorry to be a novice at this.

**Comment by bobahop** [comment]
I'm gonna try to push to yesterday's space-age branch from local...

**Comment by coriolinus** [comment]
You may have pushed the local edits to the wrong fork. Here's how to recover the changes to this one.

- Get the commit hash of your edits:
  ```sh
  $ git log -1
  commit a571f8d9844a669601cc5167b7055c75606c19d9
  ```
  The hash is the long string after "commit"
- Check out this branch. We can see from the top of the PR that this branch is called `patch-1`, so:
  ```sh
  git checkout patch-1
  ```
- Copy that commit into this branch:
  ```sh
  git cherry-pick a571f8d9844a669601cc5167b7055c75606c19d9
  ```
  Where the hash you use is the actual one you got from your commit previously. The branch head automatically updates.
- Push the branch.
  ```sh
  git push
  ```
  This PR will automatically update at that point.

**Comment by bobahop** [comment]
Which didn't work. Sigh...

```
C:\rust_projects\Exercism\rust\exercises\space-age>git push origin branch patch-1
error: src refspec branch does not match any
error: src refspec patch-1 does not match any
error: failed to push some refs to 'https://github.com/bobahop/rust.git'

C:\rust_projects\Exercism\rust>git push origin branch patch-1
error: src refspec branch does not match any
error: src refspec patch-1 does not match any
error: failed to push some refs to 'https://github.com/bobahop/rust.git'
```

**Comment by bobahop** [comment]
I think the problem is that yesterday I edited in the browser and today I edited in my local clone.

```
C:\rust_projects\Exercism\rust\exercises\space-age>git checkout patch-1
error: pathspec 'patch-1' did not match any file(s) known to git
```

**Comment by bobahop** [comment]
Okay, did git fetch and will go through your instructions again...

**Comment by bobahop** [comment]
This is turning into a royal clusterfest because my changes were a bit different from yesterday. I'm gonna delete my fork and redo it the right way from scratch.

**Comment by bobahop** [comment]
Superceded by #1047

**Pull request closed without merging**
