### PR TITLE
WIP: Exercise reordering

### PR DESCRIPTION
**Pull request by coriolinus**
Working with exercism core team on this. Feel free to comment and improve. **All other track maintenance temporarily suspended while this is in progress.** Estimated date of completion: 1 Feb 2019.

### CODE REVIEW

**Comment by petertseng** [comment]
I had to think for a bit about how one would visualise the diff produced by this, and I think I came up with a way to do that. Define the *flat representation* of a config.json as follows: Write all core exercises in order, then write all side exercises alphabetically and the core exercise that unlocks it. To visualise the diff produced by this PR, diff the *flat representation* of the original vs new `config.json`.

```diff
$ diff -u <(ruby ../problem-specifications/tree.rb --flat <(git show master:config.json)) <(ruby ../problem-specifications/tree.rb --flat config.json)
--- /proc/self/fd/11	2018-12-17 03:53:02.372319646 +0000
+++ /proc/self/fd/12	2018-12-17 03:53:02.372319646 +0000
@@ -3,19 +3,18 @@
 [deprecated] hexadecimal
 [core]
 hello-world
-pythagorean-triplet
+bracket-push
+atbash-cipher
 saddle-points
+anagram
+space-age
+sublist
 clock
 luhn
-atbash-cipher
-bracket-push
-sublist
-space-age
-macros
-poker
-anagram
 minesweeper
 parallel-letter-frequency
+macros
+poker
 forth
 
 [side]
@@ -31,13 +30,13 @@
 book-store unlocked by poker
 bowling unlocked by clock
 circular-buffer unlocked by minesweeper
-collatz-conjecture unlocked by pythagorean-triplet
+collatz-conjecture unlocked by luhn
 crypto-square unlocked by atbash-cipher
 custom-set unlocked by sublist
 decimal unlocked by poker
 diamond unlocked by luhn
 difference-of-squares unlocked by hello-world
-diffie-hellman unlocked by pythagorean-triplet
+diffie-hellman unlocked by luhn
 dominoes unlocked by poker
 dot-dsl unlocked by clock
 etl unlocked by clock
@@ -65,6 +64,7 @@
 prime-factors unlocked by hello-world
 protein-translation unlocked by anagram
 proverb unlocked by hello-world
+pythagorean-triplet unlocked by luhn
 queen-attack unlocked by clock
 rail-fence-cipher unlocked by atbash-cipher
 raindrops unlocked by hello-world
@@ -80,7 +80,7 @@
 say unlocked by saddle-points
 scale-generator unlocked by poker
 scrabble-score unlocked by saddle-points
-series unlocked by pythagorean-triplet
+series unlocked by luhn
 sieve unlocked by clock
 simple-cipher unlocked by atbash-cipher
 simple-linked-list unlocked by clock

```

**Comment by petertseng** [comment]
Oh, I actually wonder whether we're really disrupting people with pythagorean triplet so early, ever since it got the new tests in https://github.com/exercism/rust/pull/713 - the performance is now a big factor, remember how I had to do https://github.com/exercism/rust/pull/732 to make it more reasonable. While it's a fine chance to discuss asymptotic performance, having it that early is not the best for the goal of gaining fluency.

Consider this the evidence I provide in favour of the recommendation: Attempt to break off a small part of this effort that involves moving pythagorean-triplet to a more suitable place, and have it merged sooner than later.

**Comment by coriolinus** [comment]
I expect several subsequent reorderings--I'm halfway through Round 2 of the
process, and the core team is hard at work finishing implementing the rest
of Round 2 right now. There are several more rounds sketched out.
Consequently, I'd prefer not to actually break out the pythagorean-triplet
move until we can reorder everything all at once.

Also, that's a really cool way to visualize these changes. Have you linked
to `tree.rb` elsewhere?

**Comment by petertseng** [comment]
I originally wrote it for https://github.com/exercism/rust/pull/560#issuecomment-400086088 but it became so often used that I decided I needed to preserve it at https://github.com/petertseng/exercism-problem-specifications/blob/list-tracks/tree.rb

**Comment by petertseng** [comment]
Of course, back then it only supported the non-flat way of showing the track

**Comment by F3PiX** [comment]
I like the visualisation very much! I'd like to give it to other maintainers who are working through the same process. Is that okay?

**Comment by petertseng** [comment]
Well, I don't see why not. The usual deals about "no warranties, express or implied" apply, as one would expect. If people don't want to receive code, perhaps at least they at willing to receive the idea. The idea is of course independent of the code.

**Comment by F3PiX** [comment]
@maintainers/rust 
Is it possible/doable to get this reordering merged?

**Comment by coriolinus** [comment]
I want to get a more complete solution in before merging any of the
reorderings.

**Comment by coriolinus** [comment]
Superseded by #804.

**Pull request closed without merging**
