### PR TITLE
Add stubs to some exercises

### PR DESCRIPTION
**Pull request by leodasvacas**
Add stubs to leap, raindrops, bob, beer song, proverb difference of squares and sum of multiples.

### CODE REVIEW

**Comment by ijanos** [comment]
Can we modify Travis to check type check these? To approve this PR with a good conscience I would have to check every single type signature by hand.  

Probably will open an issue/pull request if I got the time, but it is likely that someone will be faster than me.

**Comment by leodasvacas** [comment]
I copy pasted all signatures from the example solutions so it's unlikely that they are incorrect, but I understand your concern. To make the manual review less painful here are the links to the examples:

[beer song](https://github.com/exercism/rust/blob/master/exercises/beer-song/example.rs)
[bob](https://github.com/exercism/rust/blob/master/exercises/bob/example.rs)
[difference of squares](https://github.com/exercism/rust/blob/master/exercises/difference-of-squares/example.rs)
[leap](https://github.com/exercism/rust/blob/master/exercises/leap/example.rs)
[proverb](https://github.com/exercism/rust/blob/master/exercises/proverb/example.rs)
[raindrops](https://github.com/exercism/rust/blob/master/exercises/raindrops/example.rs)
[sum of multiples](https://github.com/exercism/rust/blob/master/exercises/sum-of-multiples/example.rs)

**Comment by leodasvacas** [comment]
This would be particularly useful to me if it could be merged before August 12 when I will be using Exercism at a Rust workshop. I'd really appreciate if someone managed to review before that!

**Comment by ijanos** [comment]
Merging as this received no objections from anyone in a months time. Sorry for not making the merge before the 12th, I hope the workshop went well. Thank you for your contribution.

**Pull request merged**
